### PR TITLE
Python2/3 galeranotify support

### PR DESCRIPTION
**Pull request by kwizart**
Python2/3 galeranotify support

## Description
Switch galeraynotify.py.j2 to use python3 syntax by default and provide a way to support both python2/python3 variants of the script.

## Related Issue
https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/issues/167

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass. pre-merge failed with venv because I'm using python3.11 there.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by eRadical** [comment]
@elcomtik - thoughts on the failures? I don't think they're related w/ the pull request.

**Comment by elcomtik** [comment]
Me neither, I experienced such issues in other roles, but didn't have time to investigate. This Debian 9 is quite old distro(currently EoL), I would ignore this and move on with merge.

**Comment by elcomtik** [comment]
I'll check if we shouldn't update this precommit hook we use, to resolve another one issue.

**Comment by kwizart** [comment]
> I'll check if we shouldn't update this precommit hook we use, to resolve another one issue.

I've updated the pre-commit hook and confirm that it fixes the issue with me:
See also https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/pull/171

**Comment by eRadical** [comment]
@kwizart - can you please rebase this so we can see the changes and also debian 12?

**Pull request merged**
