### PR TITLE
Add more Galera notify SMTP settings

### PR DESCRIPTION
**Pull request by rutger1140**
Adds SMTP variables for the `galeranotify.py` script, to allow easier customization.

### CODE REVIEW

**Comment by elcomtik** [comment]
@rutger1140 can you rebase and fix conflicts. The defaults file had reordered lines by https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/pull/56, so it can't be merged without modification.

**Comment by rutger1140** [comment]
@elcomtik I did some rebasing. Please let me know if this works for you.

**Comment by elcomtik** [comment]
Looks good to me. Thanks @rutger1140

**Comment by elcomtik** [comment]
@mrlesmithjr In my opinion this one may be merged too.

**Pull request merged**
