### PR TITLE
Refactoring of code & molecule tests

### PR DESCRIPTION
**Pull request by elcomtik**
- fixed deprecation warnings for many modules
  - renamed tasks to keep the same style across all included files
  - renamed vars files to lowercase altered respective includes in tasks/main.yml
  - renamed temp Galera configs to the more systematic naming convention
  - renamed template for apt-pinning config
  - introduced new vars in all flavors of supported distributions to deduplicate tasks (eg. for installing packages)
  - added support for Centos 8
  - removed code for Ubuntu <= 14.04
  - moved code related do reconfigure Galera cluster to setup_cluster.yml task file & removed unnecessary tasks
  - reorganized default vars to sections according to components which they configure
  - replaced references to master by term first, because Galera is multi-master and calling only one of nodes master is misleading
  - reworked node restart logic to be more robust for the node, which needs more time to start & sync with cluster
  - bumped to minimum ansible version 2.9
  - removed unused handlers
  - removed Vagrant,added molecule tests
  - removed tests for debian8
  - disabled fedora tests until mariadb adds support for fedora 33(latest version used by docker image)
  - updated molecule tests to test on 2node cluster
  - configured group galera-cluster-nodes for each molecule test platforms
  - set default var galera_cluster_bind_interface=eth0 to match interface used by molecule tests
  - added task to clean yum cache for centos8/fedora (caused problems while testing on docker)
  - fixed lint errors
  - added var file for fedora distribution
  - bugfix for ansible issue when double interpolation used for galera wsrep address
  - added netaddr python package to requirements.txt because of used ipaddr ansible filter
  - refactored task to install MariaDb yum repository
  - changed yum repo url to use https
  - changed default mariadb version to 10.5, changed galera package name and lib path for redhat distros
  - refactored prereq pkgs for redhat and centos-8 & added install of epel for centos-8
  - refactored debian specific tasks
  - removed task which configured debian-sys-maint user (https://mariadb.org/authentication-in-mariadb-10-4/)
  - added task to wait for WSREP ready status after restarting node
  - updated README.md & CONTRIBUTORS.md

### CODE REVIEW

**Comment by elcomtik** [comment]
This PR resolves https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/issues/52, https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/issues/54 and https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/issues/55.

It also solves some of the enhancements mentioned in https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/issues/37

I squashed all commits because a lot of them were experiments used when fixing bugs. They can be seen at my repository https://github.com/elcomtik/ansible-mariadb-galera-cluster/tree/refactoring.

There shouldn't be any backward-incompatible changes related to the setting of host variables however, they should be some related to the MariaDB upgrade to version 10.5. We should add some notification to CHANGELOG.

**Comment by elcomtik** [comment]
test on one platform failed due to docker image pull error, so I triggered new tests

**Comment by elcomtik** [comment]
Again problem with pulling images, so triggering new tests

**Comment by elcomtik** [comment]
@mrlesmithjr finnaly all tests passed it's ready for review

**Comment by lekkerduidelijk** [comment]
@elcomtik Could you perhaps include PR https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/pull/53 as well? Together with your updates it's the only reason I'm running a fork of this role.

**Comment by elcomtik** [comment]
> @elcomtik Could you perhaps include PR #53 as well? Together with your updates, it's the only reason I'm running a fork of this role.

As I see it is refactoring, also. It is doable but I think it can be rebased & merged later and you would not lose contribution reference in commits. There shouldn't be any conflicts.

**Comment by lekkerduidelijk** [comment]
Ok. Good to hear. I’ll wait for the merge 👌

**Comment by mrlesmithjr** [comment]
@elcomtik Thank you so much for the hard work. I will dig into this here soon as time permits!

**Comment by elcomtik** [comment]
I'll be patient, it is a lot of changes in code 😁

**Comment by mrlesmithjr** [comment]
Apologies for this taking a long time. Been extremely busy and may need to get others involved for code review ;)

**Comment by elcomtik** [comment]
> Apologies for this taking a long time. Been extremely busy and may need to get others involved for code review ;)

All right, I appreciate that you maintain so many ansible roles. I can only imagine how much time it consumes.

**Comment by elcomtik** [comment]
Ping

**Comment by elcomtik** [comment]
Thanks @mrlesmithjr

**Pull request merged**
