### PR TITLE
Fix role to allow jinja2_native=True

### PR DESCRIPTION
**Pull request by mcpovel**
Some types will get converted when jinja2_native is set
## Description

There were some strings converted to int when jinja2_native is true. Also the list generated contained the return value of append "NONE" These were change a leats for the ubuntu/debian 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by eRadical** [comment]
LGTM, @elcomtik - thoughts?

**Comment by elcomtik** [comment]
LGTM

**Comment by eRadical** [comment]
@mcpovel - I see only debian files are fixed, can you, please, also look into other distros?

**Comment by mcpovel** [comment]
As far as I can see only the debian is using the 0x000 Hex key which failed. For the other distros only the port calculation and the list generation should apply. But I had no chance to test.

**Comment by eRadical** [comment]
@mcpovel - linting is failing because of spaces at EOF in two files.

After you fix this I'll merge.
10x

**Pull request merged**
