### PR TITLE
fix issue #199

### PR DESCRIPTION
**Pull request by roumano**
- Use a list with name and mode (optional) attribut
- Use a loop_contorl / loop_var for better read the playbook
- Change only the permission of /etc/mysql/debian.cnf from 0644 to 0600 on all debian but it's can easily update to other OS

## Description
Actually the permission is hardcoded to `0644` for all files.

## Related Issue
fix issue #199

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by eRadical** [comment]
@roumano can you please try to resolve conflicts?

**Comment by roumano** [comment]
> @roumano can you please try to resolve conflicts?

Yes no problem, it's done

**Comment by eRadical** [comment]
I still get "This branch cannot be rebased due to conflicts"

**Comment by roumano** [comment]
@eRadical , Hi, it's strange, on github it's say "This branch has no conflicts with the base branch"
are you sure, you trying to make the MR on master branch ? 

but as i don't have write access, i also see this : "Only those with write access to this repository can merge pull requests."

**Comment by eRadical** [comment]
Found it: The master branch in your fork is 9 commits behind.

Sync the fork 1st.
Then rebase permission_file branch.

**Comment by roumano** [comment]
> Found it: The master branch in your fork is 9 commits behind.
> 
> Sync the fork 1st. Then rebase permission_file branch.

Please retry now

**Comment by roumano** [comment]
@eRadical , the issue  "This branch cannot be rebased due to conflicts" is fixed for your side or not ?

**Comment by eRadical** [comment]
@roumano I have » "This branch cannot be rebased due to conflicts"

**Comment by roumano** [comment]
> @roumano I have » "This branch cannot be rebased due to conflicts"

Please try again, if it's failed again, i will create a complete new (and clean) branch  , ...

**Comment by eRadical** [comment]
@roumano - can you try again to rebase? As I think this is valuable.

**Comment by roumano** [comment]
Sync fork done, please try again

**Comment by eRadical** [comment]
In `vars/debian-12.yml` you didn't quote 0600 that's why it's failing for debian 10.

**Comment by eRadical** [comment]
For debian 12... the failure is old and I believe is from somewhere else.

**Comment by roumano** [comment]
> In `vars/debian.yml` you didn't quote 0600 that's why it's failing for debian 10 and ubuntu 18.

Thx for the information, i've fixed it.

**Comment by eRadical** [comment]
@elcomtik - LGTM, thoughts?

**Comment by elcomtik** [comment]
LGTM

**Pull request merged**
