### PR TITLE
* change ipwrap to ansible.utils.ipwrap

### LINKED ISSUE #183: Deprecation warning about "ipwrap" module
Hello,

We are running your role (v0.3.9) with Ansible core 2.14.9.

In the run, I can see this warning:

```
[DEPRECATION WARNING]: Use 'ansible.utils.ipwrap' module instead. This feature 
will be removed from ansible.netcommon in a release after 2024-01-01. 

```

I guess this warning comes from the call to "map('ipwrap')" in the template files.

Is it possible to fix this, please?

### PR DESCRIPTION
**Pull request by eRadical**
## Description
Changed to FQDN

## Related Issue
Closes #183

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:
- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by eRadical** [comment]
@elcomtik || @mrlesmithjr - should we bump up minimum Ansible req. w/ this change?

**Comment by elcomtik** [comment]
Yes, we should definitely bump minimum ansible version needed

**Comment by eRadical** [comment]
I was afraid of this answer as it begs a new question: to what version?

**Comment by eRadical** [comment]
```Starting in Ansible 2.10, most modules live in collections```
We have a requirement for Ansible 6.6.0 so we're covered w/ this.

```ansible.utils.ipwrap filter - This filter plugin is part of the ansible.utils collection version 2.12.0.```
^^^ It's this that I need to add.

**Comment by eRadical** [comment]
Upon research:
- we are ok w/ Ansible 6.6.0
- bumped ansible-core to 2.13.9 from 2.13.7
- enforced collection ansible.util - at least 2.12.0

**Pull request merged**
