### PR TITLE
Add vars & molecule for distribution Rocky 9

### PR DESCRIPTION
**Pull request by plopoyop**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by elcomtik** [comment]
LGTM
tests are failing for newer systems(centos8, rocky8, ...) because of unresolved bug. Did you test it manually?

**Comment by plopoyop** [comment]
Tests were failing because of missing binary pkill provided by `procps-ng` package.
I fix the tests in last commit. 
I created a rockylinux 9 cluster this morning. 
Should be ok now.

**Comment by elcomtik** [comment]
I think you just may have resolved the issue https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/issues/70 as well.

**Comment by plopoyop** [comment]
I have no problem running ubuntu 20 tests on my computer, so, I don't know how to check.
The error is not the same. I had "pkill not such file or directory" error on el 8-9 envs.

**Comment by elcomtik** [comment]
Never mind, I'll check it later. Merging this PR.

Thanks for your contribution!

**Pull request merged**
