### PR TITLE
chore: access for root user should be allowed from galera bind address

### PR DESCRIPTION
**Pull request by oukooveu**
it's reasonable to allow access from bind address and helpful when bind interface is not equal to `lo`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:
- [X] I have read the **CONTRIBUTING** document.
- [X] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by elcomtik** [comment]
I'm not sure how it relates to the bind interface is not equal to lo. These users are users are impersonated by client applications, eg. mysql. 

Are you sure your client is properly configured to use some of the users created currently?

In my case when I connect I use .my.cnf generated by this ansible role at /root/.my.cnf, it has defined socket auth and works like a charm. If I run the following SQL `SELECT CURRENT_USER();` I will get
`
+----------------+
| CURRENT_USER() |
+----------------+
| root@localhost |
+----------------+
`

**Comment by oukooveu** [comment]
> I'm not sure how it relates to the bind interface is not equal to lo. These users are users are impersonated by client applications, eg. mysql.

it's not only related to bind interface but mostly to absence of root privileged for all addresses except localhost as you can see below:
```
(.venv) ✔ kupchenko:ansible-mariadb-galera-cluster [ master | ✚ 1 ⚑ 1 ] ➭ molecule login --host node1
WARNING  Driver 'podman' is currently in use but the scenario config has changed and now defines 'docker'. To change drivers, run 'molecule destroy' for converged scenarios or 'molecule reset' otherwise.
INFO     Running default > login
root@node1:/# mysql -u root
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 43
Server version: 10.6.11-MariaDB-1:10.6.11+maria~deb11 mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> use mysql;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [mysql]> select user,host,select_priv from user where user='root';
+------+-----------+-------------+
| User | Host      | Select_priv |
+------+-----------+-------------+
| root | localhost | Y           |
| root | node1     | N           |
| root | 10.89.2.2 | N           |
| root | 127.0.0.1 | N           |
| root | ::1       | N           |
+------+-----------+-------------+
5 rows in set (0.002 sec)

MariaDB [mysql]> 
```

but anyway, when mariadb binds to a custom interface it's reasonable to allow connection from this interface.

**Comment by eRadical** [comment]
But in your example the connection is established via `localhost` - ie the connection will go through the unix socket.

On a production running server I do have the `bind-address` binding to the private IP of the machine. When I connect to MariaDB I get:

```
[root@ip-x-y-z-k ~]# mariadb -A 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 681548
Server version: 10.6.10-MariaDB-log MariaDB Server

MariaDB [(none)]> SELECT USER(),CURRENT_USER();
+----------------+----------------+
| USER()         | CURRENT_USER() |
+----------------+----------------+
| root@localhost | root@localhost |
+----------------+----------------+
1 row in set (0.000 sec)
MariaDB [mysql]> select user,host,select_priv from user where user='root';
+------+----------------+-------------+
| User | Host           | Select_priv |
+------+----------------+-------------+
| root | localhost      | Y           |
| root | ip-x-y-z-k     | N           |
| root | 127.0.0.1      | N           |
| root | ::1            | N           |
+------+----------------+-------------+
4 rows in set (0.001 sec)
[root@ip-x-y-z-k ~]# mariadb -A -h127.0.0.1
ERROR 2002 (HY000): Can't connect to server on '127.0.0.1' (115)
[root@ip-x-y-z-k ~]# mariadb -A -hx.y.z.k
ERROR 1045 (28000): Access denied for user 'root'@'x.y.z.k' (using password: YES)
```
Indeed you cannot connect to `127.0.0.1` because it doesn't even listen to that IP.
Same goes for `x.y.z.k` because there are no rights granted - which is what you're trying to fix.

Why do you need that if you have the unix socket avail?

Can you do a `SELECT USER(),CURRENT_USER();` - similar to @elcomtik's suggestion?

**Comment by oukooveu** [comment]
> But in your example the connection is established via `localhost` - ie the connection will go through the unix socket.

yes, it's established trough unix socket, and in this case host is always `localhost` but it's not the same to establish connection to localhost:3306.
 
> Why do you need that if you have the unix socket avail?

because containerized applications don't have access to sockets on the host or there is tcp load balancer upfront mysql or mysql is a part of service mesh... there are a lot of reasons when connection through socket is not applicable

> Can you do a `SELECT USER(),CURRENT_USER();` - similar to @elcomtik's suggestion?
```
root@node1:/# mysql -u root
MariaDB [(none)]> SELECT USER(),CURRENT_USER();
+----------------+----------------+
| USER()         | CURRENT_USER() |
+----------------+----------------+
| root@localhost | root@localhost |
+----------------+----------------+
1 row in set (0.000 sec)

MariaDB [(none)]> 
root@node1:/# mysql -u root -proot -h 10.89.2.2
MariaDB [(none)]> use mysql;
ERROR 1044 (42000): Access denied for user 'root'@'node1' to database 'mysql'
MariaDB [(none)]> 
MariaDB [(none)]> SELECT USER(),CURRENT_USER();
+------------+----------------+
| USER()     | CURRENT_USER() |
+------------+----------------+
| root@node1 | root@node1     |
+------------+----------------+
1 row in set (0.000 sec)

MariaDB [(none)]> 
```

perhaps `updating root passwords` task is not a right place to do such things: i can refactor this and just provide ability to regulate from where access is allowed, what do you think?

**Comment by eRadical** [comment]
As it is now `root` can only access the DB server via unix socket from the machine.

If we do the change it becomes available via TCP from outside.
(For now it is only available via socket forwarding through SSH.)

I think we also need more security features in this role (all toggle-able) so this might be something from a larger change where we put more checks in place.

**Comment by oukooveu** [comment]
> As it is now `root` can only access the DB server via unix socket from the machine.
> 
> If we do the change it becomes available via TCP from outside. (For now it is only available via socket forwarding through SSH.)
> 
> I think we also need more security features in this role (all toggle-able) so this might be something from a larger change where we put more checks in place.

agree, there is no reason to allow root access in this task. at the moment there is only "all or nothing" `galera_allow_root_from_any` switch, perhaps this can be refactored in the future

**Comment by elcomtik** [comment]
I would say that this role should not be used to manage containerized deployments. I hope there are better ways to do so, ideally kubernetes operator or helmchart in case of k8s orchastrator.

**Pull request closed without merging**
