### PR TITLE
add support for Ubuntu 22 (Jammy)

### PR DESCRIPTION
**Pull request by Swiff**
## Description
Added support for Ubuntu 22 (Jammy)

## Related Issue
N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by eRadical** [comment]
Can you also add a molecule test for Ubuntu 22?

**Comment by Swiff** [comment]
I have never worked with Molecule, and am a bit unsure whether to add Github Workflow, Travis or Gitlab CI configuration - I have made a "blind" commit with what I believe should be needed to run tests.

I am unsure how to rerun tests on Github?

**Comment by elcomtik** [comment]
Tests you write are great, although it fails at error:

TASK [ansible-mariadb-galera-cluster : debian | adding mariadb repo] ***********
  fatal: [node1]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.6/ubuntu jammy Release' does not have a Release file."}

**Comment by eRadical** [comment]
That might be because MariaDB does not build yet for Ubuntu 22.04.
As far as I could dug it's only for 21.10.

**Comment by scuben** [comment]
Can we re-run the tests? As far as I can see the ubuntu 20.04 is now available for mariadb 10.6 on the digitalocean mirror.

**Comment by eRadical** [comment]
Let's see if my comment triggers a rerun, otherwise you will need to make a "white space fix" commit :)

**Comment by scuben** [comment]
The actions did not rerun. @Swiff can you make an update to check if it's working now?

**Comment by elcomtik** [comment]
You can close and reopen this PR, it will trigger actions.

**Comment by eRadical** [comment]
@elcomtik - what do you think? LGTM and closes #129

**Comment by elcomtik** [comment]
LGTM

**Pull request merged**
