### PR TITLE
Workflow updates

### PR DESCRIPTION
**Pull request by kwizart**
This is a workflow update needed to fix the failing distros and pre-commit checks.

## Description
- Remove debian9
- Add debian12
- Update ansible-lint (and others) in pre-commit to fix

## Related Issue
NA

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:
- [X] I have read the **CONTRIBUTING** document.
- [X] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Some error where discovered by fixing this ansible-lint:
```
ignore-errors: Use failed_when and specify error conditions instead of using ignore_errors.
tasks/configure_root_access.yml:2 Task/Handler: configure_root_access | updating root passwords

warning[outdated-tag]: Replaced outdated tag '503' with 'no-handler', replace it to avoid future errors (warning)
tasks/mysql_databases.yml:15

no-changed-when: Commands should not change things if nothing needs doing.
tasks/setup_cluster.yml:124 Task/Handler: setup_cluster | custer bootstrap - killing lingering mysql processes to ensure mysql is stopped

no-changed-when: Commands should not change things if nothing needs doing.
tasks/setup_cluster.yml:141 Task/Handler: setup_cluster | cluster bootstrap - bootstrapping first node

Read documentation for instructions on how to ignore specific rule violations.
```

### CODE REVIEW

**Review by mrlesmithjr — APPROVED** [review]

**Comment by kwizart** [comment]
To note: I'm not sure why the debian 12 job is failing, maybe I haven't done anything to tweak the debian base image as appropriate as I'm using debian:12 whereas previous was using mrlesmithjr/debian:11 ...

**Comment by eRadical** [comment]
Yes @kwizart  - we need another image in https://github.com/mrlesmithjr/dockerfiles/tree/main 
- see details at https://github.com/mrlesmithjr/dockerfiles/blob/main/debian/11/Dockerfile

**Comment by kwizart** [comment]
OK, so I have forced-push to use mrlesmithjr/debian:12 (and defer the fix for a later PR)

**Comment by eRadical** [comment]
Now we will wait for @mrlesmithjr to merge `debian 12` in `dockerfiles` and then will see this complete also.

**Review by mrlesmithjr — APPROVED** [review]

**Comment by eRadical** [comment]
Puzzled about the last Debian 12 fail 🤕

**Comment by eRadical** [comment]
I think I found the issue.
It may be because of https://peps.python.org/pep-0668/ - I'll try a fix in debian:12 image.

**Comment by eRadical** [comment]
recheck

**Comment by eRadical** [comment]
Latest error for Debian 12 is:
```
  TASK [ansible-mariadb-galera-cluster : debian | installing pre-reqs] ***********
  fatal: [node2]: FAILED! => {"changed": false, "msg": "No package matching 'python-pymysql' is available"}
  fatal: [node1]: FAILED! => {"changed": false, "msg": "No package matching 'python-pymysql' is available"}
```

If @kwizart doesn't have time I'll try to have a go at it when I'm home!

**Comment by eRadical** [comment]
For Debian 12 we need: python3-pymysql

**Comment by eRadical** [comment]
@kwizart  - you just need to copy `vars/debian-11.yml` as `vars/debian-12.yml` (because of the `first found`).

**Comment by eRadical** [comment]
Bummer... we're in "OS contribution rabbit whole" :)

MariaDB does not build yet for Debian 12.

My Debian/Ubuntu experience ends here... so I must summon @elcomtik || @mrlesmithjr ! :|

**Comment by eRadical** [comment]
...or we could wait a few days - https://jira.mariadb.org/projects/MDEV/versions/29013 - MariaDB 10.6.15 will be released on 2023-07-27 and most probably will also contain a build for Debian 12 (see https://jira.mariadb.org/browse/MDEV-31476).

**Comment by eRadical** [comment]
Bummer, the [MDEV-31476](https://jira.mariadb.org/browse/MDEV-31476) was updated: we will not have MariaDB 10.6.x for Debian 12, only MariaDB 10.11.y.

@elcomtik && @mrlesmithjr  - do we upgrade to MariaDB 10.11 for all or only for Debian 12? What are your thoughts?

**Comment by elcomtik** [comment]
I would upgrade mariadb version for all distros. Role should be updated continuosly and we just need to inform users pin mariadb version in their deployments.

**Comment by kwizart** [comment]
I've tried to set it in the molecule config for Debian 12 to avoid to bump the default (either defaults/main.yaml or vars/debian-12) as it's probably better for end-users to select the appropriate mariadb_version themselves.
(so debian-12 users will break if they don't set a higher mariadb_version).


Then should be possible to deprecate having a default mariadb_version set at all. So it will fully defer this choice/responsibility to users.

An alternative/possible solution would be to only bump vars/debian-12.yml to a sane default.
But this move the problem, as picking 10.11 over 11.1 is hidden to users.

**Comment by eRadical** [comment]
I must say I merged even though I don't agree w/ disabling centos8.
I'll reenable it later.

**Comment by kwizart** [comment]
> I must say I merged even though I don't agree w/ disabling centos8. I'll reenable it later.

Sorry, but this was never raised. Why do you disagree ? I'm a fedora/EPEL contributor so I'm very interested in centos eco-system itslef. But centos8 is just EOL distro. specially over rocky8 and later. As I said centos stream is a a different thing tought.

**Comment by kwizart** [comment]
> I would upgrade mariadb version for all distros. Role should be updated continuosly and we just need to inform users pin mariadb version in their deployments.

I think bumping should be done at some point, but then there is a need to have a safe guard.
That way, users will not suddenly upgrade their mariadb version unexpectedly while upgrading the role.

I would go with: if early in the role the already installed mariadb version doesn't "start with" the major version set in the ansible variable and ansible_allow_upgrade_major_mariadb is False, then the role should exit early asking to set the mariadb_version.

That should prevent any surprise... (I might fill a dedicated ticket/PR for this issue)

With that said, I would probably drop the dedicated mariadb_version set in debian-12. I feel uncomfortable with this on a second tough (as  I create another place where the version is set instead in the role of global location).



Btw, thanks for having merged this PR!

**Comment by eRadical** [comment]
I have upgraded all CentOS 8 server to CentOS 8 Stream and I haven't felt any difference - of course this is anecdotal evidence but it's the simplest path for those that were and are still on CentOS 8.

The image was already moved by @mrlesmithjr to `centos8stream` which basically ensures continuous compatibility for those that upgraded from CentOS 8 to CentOS Stream.

Also we should introduce CentOS 9 Stream.

**Comment by kwizart** [comment]
So if there is a dedicated centos8stream and centos8stream tests, I'm fine. But having centos8 is miss-leading.

**Comment by eRadical** [comment]
Not necessarily since everyone knows centos8 was changed into centos8stream.

**Comment by kwizart** [comment]
Unfortunately no: centos8 (Linux, aka EOL) usage on mirrors are still dramatically high.  
So using the same name as previous Centos Linux is miss-leading and using centos8stream will highlight different pace compared to rocky8.

Properly naming things is not is not a side thing.

**Comment by eRadical** [comment]
I agree to just disagree on this :)

**Pull request merged**
